### ISSUE TITLE
[Bug] Chat messages look blurry

### ISSUE THREAD

**Issue by Imzxhir** [Qendolin/BetterUIScale#2]
Description: Now, this is a strange one. Either my eye sight has gotten worse or this is an actual bug. The title exaplains the bug, all chat messages look blurry compared to normal ones without the mod.

With the mod (GUI Scale 27):

![image](https://github.com/Qendolin/BetterUIScale/assets/98621617/e75dd253-eda4-4efb-ae5d-e3d920cabead)

Without the mod (GUI Scale 3):

![image](https://github.com/Qendolin/BetterUIScale/assets/98621617/472978e5-b1d2-4d88-9a5f-6ca8db1f4a57)

**Comment by Qendolin** [comment]
This is the ascii font atlas:
![ascii](https://github.com/Qendolin/BetterUIScale/assets/32160662/beba932a-262d-40ed-9858-11e2bb4b4c6a)
![ascii_x5](https://github.com/Qendolin/BetterUIScale/assets/32160662/8570ab85-eb34-4bd4-9628-3c9d0c29a804)

---

This is how it looks when properly scaled by 125%:  
![ascii_scaled](https://github.com/Qendolin/BetterUIScale/assets/32160662/245c2300-6741-41f7-a345-e0d0f16fe088)
![ascii_scaled_x5](https://github.com/Qendolin/BetterUIScale/assets/32160662/9cd27ade-26d6-4ea6-9964-af920830b07d)

As you can see, it's blurry, but it's also the mathematically correct result. There just aren't enough pixels on your screen to accurately scale the text.

For reference, here is how Minecraft would scale it:
![ascii_scaled_nearset](https://github.com/Qendolin/BetterUIScale/assets/32160662/039659f7-7ebe-4b88-8969-217f3d3d9975)
![ascii_scaled_nearset_x5](https://github.com/Qendolin/BetterUIScale/assets/32160662/b4f2cd8c-0a28-4c10-9370-7af90a069214)

**Comment by Imzxhir** [comment]
Oh, I see. So, is there no way to fix the blur?

**Comment by Qendolin** [comment]
No not really. Even real fonts struggle with this issue an include extra information for the individual lines in each glyph that tell the renderer if it should always try to keep it sharp or smooth.

**Comment by Imzxhir** [comment]
Couldn't you do the same thing? Tell the font renderer to make it smooth rather than blurry.

**Comment by Qendolin** [comment]
No its not as simple as that. Proper text rendering requires a huge amount of effort and is definitely out of scope for this mod.

**Comment by Imzxhir** [comment]
Understandable, I guess I will close this issue then. Thank You!
