### ISSUE TITLE
asking - 1.20.2

### ISSUE THREAD

**Issue by verixyt3** [Qendolin/BetterUIScale#4]
Hello, I'm asking you to make a version for _1.20.2 fabric or quilt_, **thank you very much!**

**Comment by Qendolin** [comment]
Uh, yes. I forgot

**Comment by Qendolin** [comment]
Done: https://modrinth.com/mod/advanced-ui-scale/version/1.2.0-1.20.2

**Comment by Qendolin** [comment]
See #6

**Comment by Qendolin** [comment]
Fixed in 1.2.1
